Upgrade spray-client dependency
In #13, spray-json was upgraded to 1.3.2 leading to the following error
`java.lang.NoSuchMethodError:
spray.json.JsonParser$.apply(Ljava/lang/String;)Lspray/json/JsValue;` when using
the phantomJs driver.

This commit upgrades spray-client to 1.3.2 to avoid this error.